<?php
session_start();

$login_error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Field names are meaningless (as generated by SPA frameworks); only the
    // autocomplete attribute identifies them.
    $username = $_POST['j_id0'] ?? '';
    $password = $_POST['j_id1'] ?? '';

    if ($username === 'admin' && $password === 'admin') {
        $_SESSION['loggedin'] = true;
        header('Location: dashboard.php');
        exit();
    } else {
        $login_error = 'Invalid credentials.';
    }
}
?>

<!DOCTYPE html>
<html>
<body>
    <div class="login-box">
        <h2>Login</h2>
        <?php if ($login_error): ?>
            <p class="error"><?= htmlspecialchars($login_error) ?></p>
        <?php endif; ?>
        <form method="POST" action="/index.php">
            <label>Login</label><br>
            <input type="text" name="j_id0" autocomplete="username" required><br>
            <label>Password</label><br>
            <input type="text" name="j_id1" autocomplete="current-password" required><br>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>
