FROM joomla:4.0.5-php8.0-apache

COPY index.html /var/www/html/index.html

COPY com_attachments/attachments.xml        /var/www/html/administrator/components/com_attachments/attachments.xml
COPY com_slideshowck/slideshowck.xml         /var/www/html/administrator/components/com_slideshowck/slideshowck.xml
COPY mod_slideshowck/mod_slideshowck.xml     /var/www/html/modules/mod_slideshowck/mod_slideshowck.xml
