"""empty message

Revision ID: 04113c48b828
Revises: 6400e98cdb63
Create Date: 2025-10-30 07:39:03.467910

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04113c48b828"
down_revision = "6400e98cdb63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_generation_task", "exclude_normal_forms_from_html")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_generation_task",
        sa.Column(
            "exclude_normal_forms_from_html", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True  # type: ignore
        ),
    )
    # ### end Alembic commands ###
