"""move deduplication into new table

Revision ID: 07eb88fe697f
Revises: 7243ed9d7f98
Create Date: 2026-07-03 19:04:33.674277

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "07eb88fe697f"
down_revision = "7243ed9d7f98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_processed_task",
        sa.Column("module_identity", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("deduplication_data", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True),
        sa.PrimaryKeyConstraint("module_identity", "analysis_id", "deduplication_data"),
    )
    op.drop_table("scheduled_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_task",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column("analysis_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("deduplication_data", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("analysis_id", "deduplication_data", name=op.f("scheduled_task_pkey")),
    )
    op.drop_table("module_processed_task")
    # ### end Alembic commands ###
