"""Add priority fields to analysis model

Revision ID: 1a7234711ca3
Revises: 7243ed9d7f98
Create Date: 2026-06-12 10:24:29.808928

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1a7234711ca3"
down_revision = "7243ed9d7f98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    task_priority_enum = sa.Enum("low", "normal", "high", name="taskpriority")
    task_priority_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("priority", task_priority_enum, nullable=True))
    op.add_column("analysis", sa.Column("desired_priority", task_priority_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis", "desired_priority")
    op.drop_column("analysis", "priority")
    # ### end Alembic commands ###

    task_priority_enum = sa.Enum("low", "normal", "high", name="taskpriority")
    task_priority_enum.drop(op.get_bind(), checkfirst=True)
