"""empty message

Revision ID: 326bcb507963
Revises: 04113c48b828
Create Date: 2025-11-07 08:24:16.599617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326bcb507963'
down_revision = '04113c48b828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_archive_request', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_archive_request', 'created_at')
    # ### end Alembic commands ###
