"""add skip_hooks field

Revision ID: 3a4f3f091ca2
Revises: 40355237ae7c
Create Date: 2024-07-03 07:21:23.040419

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a4f3f091ca2"
down_revision = "40355237ae7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report_generation_task", sa.Column("skip_hooks", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_generation_task", "skip_hooks")
    # ### end Alembic commands ###
