"""add additional_info column to task_result

Revision ID: 3d5b256854bb
Revises: 326bcb507963
Create Date: 2025-12-22 12:03:22.972080

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d5b256854bb"
down_revision = "326bcb507963"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_result", sa.Column("additional_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True)  # type: ignore
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_result", "additional_info")
    # ### end Alembic commands ###
