"""empty message

Revision ID: 4596773754db
Revises: 3a4f3f091ca2
Create Date: 2024-10-24 17:07:53.925202

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4596773754db"
down_revision = "3a4f3f091ca2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("disabled_modules", sa.String(), nullable=True))
    op.create_index(op.f("ix_analysis_disabled_modules"), "analysis", ["disabled_modules"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_disabled_modules"), table_name="analysis")
    op.drop_column("analysis", "disabled_modules")
    # ### end Alembic commands ###
