"""empty message

Revision ID: 6400e98cdb63
Revises: 6a02683b88ca
Create Date: 2025-10-27 09:52:37.057415

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6400e98cdb63"
down_revision = "6a02683b88ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report_generation_task", sa.Column("exclude_normal_forms_from_html", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_generation_task", "exclude_normal_forms_from_html")
    # ### end Alembic commands ###
