"""empty message

Revision ID: 6a02683b88ca
Revises: abf0b5022150
Create Date: 2025-10-21 19:08:54.884455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a02683b88ca'
down_revision = 'abf0b5022150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_generation_task', sa.Column('include_only_results_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_generation_task', 'include_only_results_since')
    # ### end Alembic commands ###
