"""empty message

Revision ID: ab44b9431ad1
Revises: efe3f084483b
Create Date: 2025-02-25 17:20:59.183461

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab44b9431ad1"
down_revision = "efe3f084483b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_result", sa.Column("logs", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_result", "logs")
    # ### end Alembic commands ###
