#!/bin/bash

cd $(dirname $0)/..

export EXISTING_AUTOREPORTER_REPORTS_DIRECTORY=$1

shift

docker compose $ADDITIONAL_DOCKER_COMPOSE_OPTIONS up --build autoreporter
docker compose $ADDITIONAL_DOCKER_COMPOSE_OPTIONS run -v $EXISTING_AUTOREPORTER_REPORTS_DIRECTORY:/data/ autoreporter python3 -m artemis.reporting.export.main /data/ "$@"
