#!/bin/bash

cd $(dirname $0)/..

# The following builds a string: -f docker-compose.yaml -f Artemis-modules-extra/docker-compose.yml etc.
# if any additional module repositories are cloned inside the current directory.
FILE_OPTIONS="-f docker-compose.yaml"

for DOCKER_COMPOSE_FILE in */docker-compose.yml; do
    FILE_OPTIONS="$FILE_OPTIONS -f $DOCKER_COMPOSE_FILE"
done


docker compose $FILE_OPTIONS $ADDITIONAL_DOCKER_COMPOSE_OPTIONS build autoreporter
docker compose $FILE_OPTIONS $ADDITIONAL_DOCKER_COMPOSE_OPTIONS run autoreporter python3 -m artemis.reporting.export.main "$@"
