#!/bin/bash

cd $(dirname $0)/..

. scripts/check_docker_compose

# The following builds a string: -f docker-compose.yaml -f Artemis-modules-extra/docker-compose.yml etc.
# if any additional module repositories are cloned inside the current directory.
FILE_OPTIONS="-f docker-compose.yaml"

exists() {
    [ -e "$1" ]
}

# For every single module in Artemis.
if exists */docker-compose.yml; then
    for DOCKER_COMPOSE_FILE in */docker-compose.yml; do
        FILE_OPTIONS="$FILE_OPTIONS -f $DOCKER_COMPOSE_FILE"
    done
fi

# For development version.
if exists docker-compose.temporary.yaml; then
    FILE_OPTIONS="-f docker-compose.temporary.yaml"
fi

# For additional modules in Artemis.
if exists */docker-compose.additional*.yml; then
    for DOCKER_COMPOSE_FILE in */docker-compose.additional*.yml; do
        FILE_OPTIONS="$FILE_OPTIONS -f $DOCKER_COMPOSE_FILE"
    done
fi

docker compose $FILE_OPTIONS $ADDITIONAL_DOCKER_COMPOSE_OPTIONS "$@"
