#!/bin/bash

cd $(dirname $0)/..

DOCKER_CONFIGS_STRING="$(scripts/find_docker_compose_files --mode=production --docker-compose-string) "
DOCKER_CONFIGS_STRING+="$(scripts/find_docker_compose_files --mode=development --docker-compose-string)"

docker compose $DOCKER_CONFIGS_STRING $ADDITIONAL_DOCKER_COMPOSE_OPTIONS "$@"
