#!/bin/bash

cd $(dirname $0)/..


MODE="production"
ARGS=()

for arg in "$@"; do
  case "$arg" in
    --mode=*)
      MODE="${arg#*=}"
      ;;
    *)
      ARGS+=("$arg")
      ;;
  esac
done

DOCKER_CONFIGS_STRING="$(scripts/find_docker_compose_files --mode=$MODE --docker-compose-string)"
docker compose $DOCKER_CONFIGS_STRING $ADDITIONAL_DOCKER_COMPOSE_OPTIONS "${ARGS[@]}"
