#!/bin/bash

cd $(dirname $0)/..

# We don't use `-d` here so that the user sees the logs by default.
. scripts/run_docker_compose up --build \
    --scale=karton-wp_scanner=3 \
    --scale=karton-identifier=3 \
    --scale=karton-port_scanner=5 \
    --scale=karton-wordpress_plugins=5 \
    --scale=karton-sqlmap=5 \
    --scale=karton-nuclei=5 \
    --scale=karton-bruter=5
