#!/bin/bash

cd `dirname $0`/..

docker compose -f docker-compose.test.yaml build test
docker compose -f docker-compose.test.yaml up -d postgres-test
docker compose -f docker-compose.test.yaml run test python -m unittest discover test.long_running
