#!/bin/bash

LOCALES="pl_PL en_US"

cd $(dirname $0)/..

if [ ! -d venv ]
then
    python3 -m venv venv
fi

. venv/bin/activate

pip install Babel==2.12.1 Jinja2==3.1.2

(
    for template_file_name in `find artemis/ | grep \\.jinja2$`
    do
        dirname $template_file_name
    done
) | sort | uniq | (
    while read template_directory_name
    do
        mkdir -p $template_directory_name/translations
        pybabel extract \
            --omit-header \
            --strip-comments \
            -F babel.cfg \
            -o $template_directory_name/translations/messages.pot \
            $template_directory_name
        for locale in $LOCALES
        do
            mkdir -p $template_directory_name/translations/$locale/LC_MESSAGES
            pybabel update \
                --omit-header \
                 --init-missing \
                -l $locale \
                -i $template_directory_name/translations/messages.pot \
                -d $template_directory_name/translations/

           # Remove the last newline so that we don't conflict with linters
           sed -i -z '$ s/\n$//' $template_directory_name/translations/$locale/LC_MESSAGES/messages.po
        done
    done
)
