import unittest
from unittest.mock import MagicMock, patch

from artemis.waf_detect import (
    WAFType,
    _check_block_page,
    _check_cookie_signatures,
    _check_headers,
    detect_waf,
)


class TestCheckHeaders(unittest.TestCase):
    def test_cloudflare_detection(self) -> None:
        result = _check_headers({"server": "cloudflare"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.CLOUDFLARE)
        self.assertEqual(result.confidence, "high")

        result = _check_headers({"cf-ray": "abc123-IAD"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.CLOUDFLARE)

        result = _check_headers({"cf-mitigated": "challenge"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.CLOUDFLARE)

        result = _check_headers({"server": "CLOUDFLARE"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.CLOUDFLARE)

    def test_common_waf_headers(self) -> None:
        cases = [
            ({"x-sucuri-id": "12345"}, WAFType.SUCURI),
            ({"server": "AkamaiGHost"}, WAFType.AKAMAI),
            ({"akamai-grn": "some-value"}, WAFType.AKAMAI),
            ({"x-cdn": "Imperva"}, WAFType.IMPERVA),
            ({"set-cookie": "incap_ses_12345=abc"}, WAFType.IMPERVA),
            ({"x-amzn-waf-action": "block"}, WAFType.AWS_WAF),
            ({"server": "CloudFront"}, WAFType.CLOUDFRONT),
            ({"server": "Apache/2.4.41 mod_security/2.9.3"}, WAFType.MODSECURITY),
            ({"server": "BigIP"}, WAFType.F5_BIG_IP),
            ({"set-cookie": "BIGipServerpool_web=123456"}, WAFType.F5_BIG_IP),
            ({"server": "Barracuda/5.0"}, WAFType.BARRACUDA),
            ({"server": "FortiWeb"}, WAFType.FORTIWEB),
            ({"set-cookie": "fortiwafsid=abc123"}, WAFType.FORTIWEB),
            ({"x-fastly-request-id": "abc123"}, WAFType.FASTLY),
            ({"x-sp-waf": "1"}, WAFType.STACKPATH),
            ({"server": "nginx-wallarm"}, WAFType.WALLARM),
            ({"set-cookie": "rbzid=abc123"}, WAFType.REBLAZE),
            ({"set-cookie": "ns_af=abc"}, WAFType.CITRIX_NETSCALER),
            ({"x-sl-compstate": "abc"}, WAFType.RADWARE),
        ]
        for headers, expected_type in cases:
            result = _check_headers(headers)
            assert result is not None, f"Expected detection for {headers}"
            self.assertEqual(result.waf_type, expected_type, f"Wrong WAF type for {headers}")

    def test_no_waf(self) -> None:
        self.assertIsNone(_check_headers({"server": "nginx/1.18.0", "content-type": "text/html"}))
        self.assertIsNone(_check_headers({}))

    def test_multiple_detections_picks_highest_confidence(self) -> None:
        result = _check_headers({"cf-ray": "abc123", "cf-cache-status": "HIT"})
        assert result is not None
        self.assertEqual(result.confidence, "high")


class TestCheckCookieSignatures(unittest.TestCase):
    def test_known_cookies(self) -> None:
        result = _check_cookie_signatures({"set-cookie": "incap_ses_123=abc; visid_incap_456=def"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.IMPERVA)

        result = _check_cookie_signatures({"set-cookie": "BIGipServerpool=123456"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.F5_BIG_IP)

        result = _check_cookie_signatures({"set-cookie": "aws-waf-token=abc123"})
        assert result is not None
        self.assertEqual(result.waf_type, WAFType.AWS_WAF)

    def test_no_waf_cookie(self) -> None:
        self.assertIsNone(_check_cookie_signatures({"set-cookie": "session=abc123"}))
        self.assertIsNone(_check_cookie_signatures({"server": "nginx"}))


class TestCheckBlockPage(unittest.TestCase):
    def test_known_block_pages(self) -> None:
        cases = [
            ("<html><title>Attention Required! | Cloudflare</title></html>", WAFType.CLOUDFLARE),
            ("<html>challenges.cloudflare.com/cdn-cgi/challenge</html>", WAFType.CLOUDFLARE),
            ("<h2>Access Denied - Sucuri Website Firewall</h2>", WAFType.SUCURI),
            ("<p>Powered by Imperva</p><p>Incapsula incident ID: 123456</p>", WAFType.IMPERVA),
            ("<html>Request unsuccessful. Incapsula incident ID: 123</html>", WAFType.IMPERVA),
            ("<html><body>ModSecurity Action</body></html>", WAFType.MODSECURITY),
            ("<html>The requested URL was rejected. Your support ID is: 12345678901234</html>", WAFType.F5_BIG_IP),
            ("<h1>403 ERROR</h1><p>The Amazon CloudFront distribution is configured</p>", WAFType.AWS_WAF),
            ("<p>Generated by Wordfence at Mon, 10 Mar 2026</p>", WAFType.WORDFENCE),
            ("<html>Barracuda Web Application Firewall has blocked this request.</html>", WAFType.BARRACUDA),
            ("<html>FortiWeb blocked this request</html>", WAFType.FORTIWEB),
            ("<html>Citrix Application Firewall has blocked this request</html>", WAFType.CITRIX_NETSCALER),
            ("<html>Unauthorized Activity Has Been Detected by Radware</html>", WAFType.RADWARE),
        ]
        for content, expected_type in cases:
            result = _check_block_page(content)
            assert result is not None, f"Expected detection for {expected_type.value}"
            self.assertEqual(result.waf_type, expected_type)

    def test_blocks_payloads_flag(self) -> None:
        result = _check_block_page("<html>ModSecurity Action</html>", status_code=403)
        assert result is not None
        self.assertTrue(result.blocks_payloads)

        result = _check_block_page("<html>ModSecurity Action</html>", status_code=200)
        assert result is not None
        self.assertFalse(result.blocks_payloads)

    def test_no_waf_content(self) -> None:
        self.assertIsNone(_check_block_page("<html><body><h1>Welcome</h1></body></html>"))
        self.assertIsNone(_check_block_page(""))


class TestDetectWAF(unittest.TestCase):
    URL = "http://example.com"

    def setUp(self) -> None:
        detect_waf.cache_clear()

    def _make_response(self, headers: dict, status_code: int = 200, content: str = "<html>OK</html>") -> MagicMock:
        resp = MagicMock()
        resp.headers = headers
        resp.status_code = status_code
        resp.content = content
        return resp

    @patch("artemis.waf_detect.http_requests")
    def test_detect_cloudflare_from_headers(self, mock_http: MagicMock) -> None:
        mock_http.get.return_value = self._make_response({"server": "cloudflare", "cf-ray": "abc123"})

        result = detect_waf(self.URL)
        self.assertTrue(result.detected)
        self.assertEqual(result.waf_type, WAFType.CLOUDFLARE)
        self.assertEqual(result.confidence, "high")

    @patch("artemis.waf_detect.http_requests")
    def test_detect_waf_from_probe_block(self, mock_http: MagicMock) -> None:
        mock_http.get.side_effect = [
            self._make_response({"server": "nginx"}),
            self._make_response({}, status_code=403, content="<html>ModSecurity Action</html>"),
        ]

        result = detect_waf(self.URL)
        self.assertTrue(result.detected)
        self.assertEqual(result.waf_type, WAFType.MODSECURITY)
        self.assertTrue(result.blocks_payloads)

    @patch("artemis.waf_detect.http_requests")
    def test_detect_no_waf(self, mock_http: MagicMock) -> None:
        mock_http.get.return_value = self._make_response({"server": "nginx/1.18.0"})
        self.assertFalse(detect_waf(self.URL).detected)

    @patch("artemis.waf_detect.http_requests")
    def test_connection_failures(self, mock_http: MagicMock) -> None:
        mock_http.get.side_effect = Exception("Connection refused")
        result = detect_waf(self.URL)
        self.assertFalse(result.detected)
        self.assertEqual(result.evidence, "Connection failed")

    @patch("artemis.waf_detect.http_requests")
    def test_probes_dropped(self, mock_http: MagicMock) -> None:
        mock_http.get.side_effect = [self._make_response({"server": "nginx"})] + [Exception("reset")] * 7

        result = detect_waf(self.URL)
        self.assertTrue(result.detected)
        self.assertTrue(result.blocks_payloads)

    @patch("artemis.waf_detect.http_requests")
    def test_detect_from_cookies(self, mock_http: MagicMock) -> None:
        mock_http.get.return_value = self._make_response(
            {"server": "nginx", "set-cookie": "incap_ses_123=abc; visid_incap_456=def"}
        )

        result = detect_waf(self.URL)
        self.assertTrue(result.detected)
        self.assertEqual(result.waf_type, WAFType.IMPERVA)

    @patch("artemis.waf_detect.http_requests")
    def test_block_status_codes(self, mock_http: MagicMock) -> None:
        for status_code in [403, 406, 429, 503]:
            detect_waf.cache_clear()
            mock_http.get.side_effect = [
                self._make_response({"server": "nginx"}),
                self._make_response({"server": "nginx"}, status_code=status_code, content="<html>Blocked</html>"),
            ]
            self.assertTrue(detect_waf(self.URL).detected, f"Failed for status {status_code}")

    @patch("artemis.waf_detect.http_requests")
    def test_caching(self, mock_http: MagicMock) -> None:
        mock_http.get.return_value = self._make_response({"server": "cloudflare"})

        result1 = detect_waf(self.URL)
        result2 = detect_waf(self.URL)
        self.assertEqual(result1.waf_type, result2.waf_type)
        self.assertEqual(mock_http.get.call_count, 1)


if __name__ == "__main__":
    unittest.main()
