name: Compile requirements

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-alpine3.20
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
            ref: ${{ github.head_ref }}

      - run: apk add bash
      - run: pip install pip-tools --break-system-packages
      - run: ./scripts/compile-requirements
      - run: pwd
      - run: ls -a

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add requirements.txt
          git diff --cached --quiet || git commit -m "Recompile requirements"
          git push
