name: "tests"
on:
  pull_request:
    branches: [ '**' ]

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: set RUNNING_ON_GITHUB in env.test
        run: echo RUNNING_ON_GITHUB=1 >> env.test
      - name: run unit tests
        run: bash ./scripts/test-unit

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: set RUNNING_ON_GITHUB in env.test
        run: echo RUNNING_ON_GITHUB=1 >> env.test
      - name: run e2e tests
        run: bash ./scripts/test-e2e
